### ISSUE TITLE
Master password no longer being accept on iOS

### ISSUE THREAD

**Issue by shbrainard** [bitwarden/ios#1002]
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to Bitwarden app
2. Enter email
3. Enter password

### Expected Result

Successful login

### Actual Result

"An error has occurred.  Username or password is incorrect.  Try again"

### Additional Context

Today my iOS app stopped accepting my Master Password.  Still works in Chrome and desktop app on macOS.  Deleted app and reinstalled latest version from App Store on iOS (2024.9.2) and still not working.  Updated to most recent version of iOS (17.7) and still not working.

### Build Version

2024.9.2

### Environment Details

iPhone 13 mini, iOS 17.7

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by shbrainard** [comment]
While perhaps not reproducible, if you check other Github Issues on this repo, or this thread:

https://community.bitwarden.com/t/cannot-log-in-on-iphone/56389/8

or Reddit, you will find numerous other users experiencing this same exact issue.  I would recommend reopening and addressing this.
