### ISSUE TITLE
No way to connect any more on latest IOS Bitwarden App (2024.9.2)

### ISSUE THREAD

**Issue by dawstudiocenter** [bitwarden/ios#1006]
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

My Language is french so the description used below could be slightly different than expected in app for english people.
1. Go to 'Default Login page.'
2. Enter 'user email' as usual.
3. Tap on Connection and select 'self-hosted'
4. Enter 'self-hosted server URL' as usual.
5. Tap on 'Continue'
6. Enter 'user main key/password' 
7. Tap on 'Connect with main password'

### Expected Result

Enter the app and get the list of managed accounts credentials

### Actual Result

"An error has occured message" when providing main password

### Build Version

2024.9.2 

### Environment Details

- iPhone 14
- iOS 18.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by LinuxEclipsed** [comment]
I am experiencing the same issue described by OP with the latest IOS app release. I am unable to access the vault via the app. Andriod and web version work as expected.
