### ISSUE TITLE
Unusable on iOS 18.1 Public Beta

### ISSUE THREAD

**Issue by nkasco** [bitwarden/ios#1025]
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

iOS 18.1 - login attempts to self hosted result in "An error has occurred." Literally unusable, can't retrieve pw hint or anything.

I've reinstalled the app, and ensured my self hosted instance is fully up to date.

### Expected Result

.

### Actual Result

.

### Build Version

2024.9.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. However, some users who use Vaultwarden with their self-hosted server have reported that updating Vaultwarden has resolved this issue. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by nkasco** [comment]
@Neonwarden How can I get more info around the failure beyond "An error has occurred"? I could probably give you more meaningful info but the app doesn't expose much.

**Comment by nkasco** [comment]
Also, #891 clearly it isn't just me

**Comment by nkasco** [comment]
@Neonwarden I hooked my phone up to XCode and pulled the error from the console. How do I proceed?

error	18:54:36.527312-0400	Bitwarden	-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID. inputModality = Keyboard, inputOperation = <null selector>, customInfoType = UIEmojiSearchOperations
