### ISSUE TITLE
Autofill for ios apps not recognizing creds

### ISSUE THREAD

**Issue by Omzig** [bitwarden/ios#1107]
### Steps To Reproduce

1. Go to 'myCricket app'
2. Tap on 'password'
3. Tap on 'bitwarden' to get password

### Expected Result

login should be shown in the list

### Actual Result

list is blank and you have to search

### Additional Context

The only way to find your credential is to search for myCricket, i have not been able to find 1 app that bitwarden was able to help me find my password or auto search for.

if you use apple keys where they store passwords, they are able to identify credentials that match up with the app

there is an open discussion about it, but there isn't any good solutions on the thread
- https://community.bitwarden.com/t/auto-fill-on-ios-and-applications/64083/9

### Build Version

2024.9.2 (1106)

### Environment Details

- Device: iphone 13 pro max
- OS Ver: 17.7

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment]
Hi there,

Thank you for your report!

Please take a look at this [guide](https://bitwarden.com/help/uri-match-detection/#obtaining-uris-for-mobile-apps) on obtaining URLs for mobile apps. Also, developers of iOS applications must explicitly make their app compatible for autofill by claiming their domain.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

The issue here will be closed.

Thanks!
