### ISSUE TITLE
Duplicate "Hide My Email" suggestions when tapping email address field on login

### ISSUE THREAD

**Issue by ghost** [bitwarden/ios#1112]
### Steps To Reproduce

**Description:**

When attempting to log in to Bitwarden on iOS, tapping on the email address field brings up Apple’s "Hide My Email" feature in the keyboard suggestion bar twice, rather than showing "Hide My Email" once alongside the default email from Contacts. This issue occurs when there is no pre-existing Bitwarden password stored in the Apple Passwords app.

**Steps to Reproduce:**

1. Open the Bitwarden app on an iPhone 13 Pro.
2. Tap the email address field on the login screen.
3. Ensure there is no Bitwarden password saved in the Apple Passwords app.

### Expected Result

**Expected Result:**

The keyboard suggestion bar should display Apple’s "Hide My Email" feature once, along with the primary email address from Contacts.

### Actual Result

**Actual Result:**

The keyboard suggestion bar displays "Hide My Email" twice, with no option to auto-fill from the default email address in Contacts.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/33b8439b-3a61-4f36-a46c-e4d9481e63e4)

### Additional Context

**Additional Notes:**

This behavior may lead to confusion for users expecting to see their primary email auto-fill option alongside the "Hide My Email" suggestion.

### Build Version

- Bitwarden app version: 2024.10.0

### Environment Details

**Device Information:**

- Device: iPhone 13 Pro
- iOS version: 18.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
