### ISSUE TITLE
Remove useless UI elements to count number of items in collection

### ISSUE THREAD

**Issue by tavern2782** [bitwarden/ios#1179]
### Steps To Reproduce

1. Open app

### Expected Result

A better UI

### Actual Result

A UI designed by a child

### Additional Context

We don't need the useless UI element that counts the number of items in a collection. No one cares. Remove it.

### Build Version

2024.11.0 (1680)

### What server are you connecting to?

US

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by tavern2782** [comment]
https://github.com/bitwarden/ios/blob/70003811fcd96560478a3a242bfa5a94e89e9a77/BitwardenShared/UI/Vault/Views/VaultListSectionView.swift#L47

Change the bool here to `false` to remove this nonsense

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by tavern2782** [comment]
It's not a request. It's a demand. I'll put in the PR myself if the maintainers are too lazy to do it.
