### ISSUE TITLE
Ui gets laggy

### ISSUE THREAD

**Issue by speedy1804** [bitwarden/ios#1187]
### Steps To Reproduce

1. Open a password
2. Press and hold your finger on the URL
3. Slide up and and down with that finger while pressing the URL
4. —> Ui gets laggy as seen in the Attachments

### Expected Result

It is to be expected that the Ui continues to move smoothly and that the animation does not contain any jerks.  

### Actual Result

The Ui has much performance issues.

### Screenshots or Videos

https://github.com/user-attachments/assets/19f61937-b80d-41b7-b519-4f7b79751f46

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.11.0 (1680)  -------- Device --------  Model: iPhone14,7 OS: iOS 18.1.1  ------- CI Info --------  Branch: release/2024.11-rc1 CI Run Attempt: 1 CI Run ID: 11787735651 CI Run Number: 411 Commit hash: 2a079717b7a63d8e5b4618de554b0d4dfc576ff1 Compiler Flags:  Repository: https://github.com/bitwarden/ios

### What server are you connecting to?

US

### Environment Details

- Device: iPhone 14
-  OS: iOS 18.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
hello @speedy1804 

I attempted to reproduce the issue you are experiencing and was unable to do so. My app is working fine as expected; I would ask that you restart your device. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
