### ISSUE TITLE
Unable to Login to Vault

### ISSUE THREAD

**Issue by elibrody** [bitwarden/ios#1199]
### Steps To Reproduce

1. Go to 'App'
2. Tap on 'Login'
3. try entering master password 

### Expected Result

Successful signin

### Actual Result

I get an error has occurred the request timed out

### Build Version

2024.11.0

### What server are you connecting to?

US

### Environment Details

Device is an iPhone 16 Pro Max running IOS 18.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there, 

Thanks for reporting this! Can you try logging in on your iPhone 16 now? 

If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
