### ISSUE TITLE
[Bug] Bitwarden logs out of my account after closing the app from the App Switcher

### ISSUE THREAD

**Issue by MahdiNazemi** [bitwarden/ios#772]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Set the vault timeout time to 4 hours and the action to logout.
2. Close the app from the App Switcher.
3. Re-open the app.
4. You will be asked to log in again although 4 hours has not passed yet.

### Expected Result

Keep the user logged in for four hours.

### Actual Result

Bitwarden logs the user out immediately.

### Build Version

2024.7.2

### Environment Details

iPhone 15 Pro Max

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software - the app restarting will result in the account being logged out, much like the conditions in the web app and browser extensions detailed in this article: https://bitwarden.com/help/vault-timeout/

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
