### ISSUE TITLE
Autofill broken on iOS 18

### ISSUE THREAD

**Issue by NDolensek** [bitwarden/ios#792]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open Safari (or any other app with a generic text field)
2. Tap on the text field/URL field so the text editing bubble appears
3. Click on "Autofill", then click on "Passwords"
4. "AutoFill Unavailable, the developer of Bitwarden needs to update it to work with this feature" error appears, with autofill not working

<img width="460" alt="image" src="https://github.com/user-attachments/assets/8fe185ee-d56e-4cb7-8cf8-33d4991044e9">

### Expected Result

Autofill should fill in the text field using Bitwarden info.

### Actual Result

Autofill is non-functional.

### Build Version

iOS beta 2024.7.3 (1263)

### Environment Details

- Device: iPhone 15 Pro Max
- OS: iOS 18.1 Beta 1 (22B5007p) (but had this error for a while, on iOS 18.0 developer betas 2, 3, 4, and public betas 1 and 2.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software - at this time it is expected to see this error in the iOS 18 betas.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by PartyingChair** [comment]
Is there any plan to do this now that we’re nearly on 18.1?
