### ISSUE TITLE
IOS-EDGE automatic filling password BUG

### ISSUE THREAD

**Issue by 3377** [bitwarden/ios#796]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1、在bitwarden edge ios 15.1使用官方库连接的情况下，登录网站时可以通过键盘方式填充，但填充后的密码实际上无法登录。
2、我确认此密码是对的，也正常保存在了bitwarden里面。
3、同样的方式在safari里面是可以正常登录使用的
1. When bitwarden edge ios 15.1 uses the official library connection, you can fill in the password through the keyboard when logging in to the website, but the filled password cannot actually be logged in.
2. I confirm that the password is correct and is saved in bitwarden normally.
3. The same method can be used to log in normally in Safari.

### Expected Result

1、账户填好，密码处随便填个字再填充就可以使用。
2、直接填充，密码处随便改下，再填充，也可以使用
1. Fill in the account, fill in any word in the password, and then you can use it.
2. Fill it in directly, change the password and fill it in again, it can also be used.

### Actual Result

1、账户填好，密码处随便填个字再填充就可以使用。
2、直接填充，密码处随便改下，再填充，也可以使用
1. Fill in the account, fill in any word in the password, and then you can use it.
2. Fill it in directly, change the password and fill it in again, it can also be used.

### Additional Context

测试网站
www.nodeseek.com
爱快内网 10.1.1.1/login#login

### Build Version

7.3和7.1都测试过

### Environment Details

iphone13pro max ios15.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by 3377** [comment]
https://github.com/user-attachments/assets/f8890d36-4feb-4afd-846a-cefed6c675e4

这是实际演示的视频操作，多个网站会这样

**Comment by Greenderella** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
