### ISSUE TITLE
Account section is not working

### ISSUE THREAD

**Issue by Naxterra** [bitwarden/ios#860]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to top left corner of the app
2. Click on name (initials)
3. It looks like it is trying to open something, showing a black transparent popup, but nothing is happening

### Expected Result

App should show Account names

### Actual Result

Nothing is happening.

### Build Version

2024.8.0 (284)

### Environment Details

iPhone 15 Pro Max
iOS Dev Beta 7 (22A5346a)

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
I attempted to reproduce your issue and was unable to do so. Can you try uninstalling the app and reinstalling it to see if that makes a difference? 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by BBGhub** [comment]
User responded: I also deleted and reinstalled the app. Still has the same issue.
@jtodddd

**Comment by jatin-bansal-21** [comment]
I am also facing the same issue and I have tried uninstalling and installing the app multiple times. I have a screen recording for the same. Even when I have multiple accounts the account switcher drop down does not show properly.

https://github.com/user-attachments/assets/b1b8a736-b6c4-4a02-9dcb-ffc7a2762b55

**Comment by Naxterra** [comment]
Issue exists in the new official build 2024.8.1 (1052) too

**Comment by say4n** [comment]
+1, using App Store build (1052) on iPhone 15 Pro.

https://github.com/user-attachments/assets/61819c37-0554-4536-b6e2-34b33ca65b9b

**Comment by AlexZorzi** [comment]
By putting your iPhone in Landscape mode you are able to access the multi account dialog.
Seems to be just a Ui issue where the dialog is behind the top bar when in portrait mode.

**Comment by Naxterra** [comment]
This is fixed in 2024.9.1
