### ISSUE TITLE
Context Menu Autofill Not Working (iOS 18)

### ISSUE THREAD

**Issue by zoltrons** [bitwarden/ios#916]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to 'any app with text field'
2. Tap on 'text field twice'
3. Press to 'autofill'
4. Tap on 'passwords'

### Expected Result

Opening the autofill menu

### Actual Result

AutoFill Unavailable
The developer of "Bitwarden" needs to update it to work with this feature. You can open "Bitwarden" to copy information to fill.

### Screenshots or Videos

https://github.com/user-attachments/assets/29eeab88-f4b7-4b15-83ad-c075a0086731

### Additional Context

I think apple finally open up autofill context menu button for third-party apps with iOS 18. So an implementation need for this feature.

### Build Version

2024.8.1 (1052)

### Environment Details

Device: iPhone 15
OS: iOS 18 RC

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by zoltrons** [comment]
> Hi there,
> 
> 
> 
> I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 
> 
> 
> 
> Thanks!

Are you tried on iOS 18? And in os settings, only password manager enabled is bitwarden?

**Comment by zoltrons** [comment]
More people reporting the issue on Reddit.
https://www.reddit.com/r/Bitwarden/comments/1fiy4m4/autofill_by_long_pressing_text_field_in_ios_18_is/

**Comment by lcasale** [comment]
Having the same issue on public release iOS. In prior iOS releases it wouldn't even load Bitwarden from the context menu but at least gives this error in iOS18.

https://github.com/user-attachments/assets/c1e9856f-e129-400e-a27b-6a9ca959a8d6

![image](https://github.com/user-attachments/assets/5a580234-338c-487a-bb11-9f6f5735e387)

**Comment by aneutron** [comment]
I have the same issue, I have tried the following:
- First, reboot the device.
- Then disable autofill for Bitwarden and Re-enable it.
- Then disable and re-enable the whole autofill feature.
- Reinstall the app and try the 3 above scenarios.
 
Still no luck. It works without an issue on Chrome and other apps, but not on Safari.
 
Versions:
- iOS 18.0 (22A3354, EU build if that helps)
- 2024.9.1 (1092)

**Comment by jmalexan** [comment]
I was looking into this this morning to see if this functionality could be implemented easily, but I realized there's some UI work that would be required that's above my pay grade as someone who's not looked at this codebase before.  Here's what I dug up though, in case it helps the next person:
- [This key](https://developer.apple.com/documentation/bundleresources/information_property_list/providestexttoinsert) needs to be added to the appropriate dictionary in the plist
- [This function](https://developer.apple.com/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareInterfaceForUserChoosingTextToInsert()) needs to be implemented in BitwardenAutoFillExtension/CredentialProviderViewController.swift
- UI needs to be added to the pop-up vault list that allows for drilling into a vault item's details and selecting the specific thing to autofill in that item (at the very least should allow selecting between username and password, but ideally would allow selecting any text field in a vault item).
- Needs to call [this function](https://developer.apple.com/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeRequest(withTextToInsert:completionHandler:)) to pass the text value back to the system, instead of [this one](https://developer.apple.com/documentation/authenticationservices/ascredentialproviderextensioncontext/completerequest(withselectedcredential:completionhandler:))

**Comment by zizzfizzix** [comment]
Looks like it's being worked on in #1178.

**Comment by zoltrons** [comment]
This feature still not works as expected. 
https://github.com/user-attachments/assets/d3939177-a0a5-4eee-9c2c-ab1221524d63

**Comment by zizzfizzix** [comment]
This was merged after the Dec release so would likely end up in the next one.
