### ISSUE TITLE
I cannot log into the new iOS app

### ISSUE THREAD

**Issue by fabriziobagala** [bitwarden/ios#936]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Install or reinstall the app from the App Store
2. Tap on the Bitwarden icon on the homepage
3. Enter the credentials and log in

### Expected Result

I can log in and use the app.

### Actual Result

I cannot log in and receive the following error:
> An error has occurred
> Username or password is incorrect. Try again.

### Additional Context

I found this workaround. In the Bitwarden login screen:

1. Tap on the drop-down menu 'Logging in on:'
2. Select 'bitwarden.eu'
4. Tap one more time on the drop-down menu 'Logging in on:'
5. Select 'bitwarden.com'
6. Enter the credentials and log in

### Build Version

2024.8.1 (1052)

### Environment Details

- Device: iPhone 11 Pro
- Version: 17.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by CRASH-Tech** [comment]
+1

**Comment by HarryLovesCode** [comment]
+1

Same here, thought it might be iOS 18.

Device: iPhone 12 pro max
Version: 18.0

No issues on Android, Chrome etc.

Tried workaround also.

**Comment by jtodddd** [comment]
Hi there,

Can you give it another try now and see if it is still happening?

If so, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
