### ISSUE TITLE
Local Network Access permission missing

### ISSUE THREAD

**Issue by 5m4u66y** [bitwarden/ios#959]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Connect your iOS device to your private network WiFi
2. Open Bitwarden App and try to connect to your selfhosted server on the same private network

### Expected Result

iOS App should connect to the server or ask for Local Network Access permission if it is not already enabled for Bitwarden App.

### Actual Result

Connection attempt fails after a timeout. If you go to iOS Settings / Bitwarden there is no option to enable Local Network Access, and Bitwarden App is not listed if you go to Settings / Privacy & Security/ Local Network.

### Additional Context

There is the same issue if you have your selfhosted server already connected to the app and you try to Sync your vault when connected to your private network.

### Build Version

2029.9.1 (1092)

### Environment Details

- iPhone 12 - OS Version : 17.7

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

This was also not an option on our non-native apps. We would not recommend setting up your environment like that since if you get a 403 error outside of home network, you will get logged out. 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
