### ISSUE TITLE
Autocorrection should be disabled for search field

### ISSUE THREAD

**Issue by holow29** [bitwarden/ios#975]
### Steps To Reproduce

1. Be on iOS device with autocorrect enabled
2. Type webauthn or nyt, etc. in Bitwarden iOS app "search" field
3. Click search
4. If you aren't fast enough, autocorrect will change it to something else and the results will no longer be valid

### Expected Result

Autocorrect does not alter searched text

### Actual Result

Autocorrect alters the text.

### Additional Context

Search field needs autocorrection type property changed: https://developer.apple.com/documentation/uikit/uitextinputtraits/1624453-autocorrectiontype

### Build Version

1106

### Environment Details

- Device: iPhone 14 Pro
- iOS 18

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Can you make sure your browser's built-in password manager is disabled? You can follow this guide to do so: https://bitwarden.com/help/disable-browser-autofill/
Often, when a browser's built-in password manager contains an item for signing into the Bitwarden vault, it will attempt to autofill a vault item's password field. 

We also do not recommend storing your master password in another password manager and instead writing it down and storing it in a safe place. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by holow29** [comment]
Your response has nothing to do with this issue. If you search "webauthn" in the search field of the iOS app and then click "search," autocorrect will activate and change it to something else (if autocorrect is active in iOS)

**Comment by holow29** [comment]
@Neonwarden How did you try to reproduce? Your response has nothing to do with this issue and does not even appear to involve the iOS app. If you search "webauthn" in the search field of the iOS app and then click "search," autocorrect will activate and change it to something else (if autocorrect is active in iOS). This issue should be re-opened.

**Comment by luc-bw** [comment]
Hi @holow29,

My apologies! There was a misunderstanding that it could be the OS autofill methods which were causing the text to change. We understand that this is the keyboard autocorrect function being referred to. I was able to reproduce this and will re-open.

Thank you for the report!
